### ISSUE TITLE
(node:40) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'filename' of undefined

### ISSUE THREAD

**Issue by sukesh-ak** [opendatacam/opendatacam#635]
Hi guys,

Need help. I am trying to get `opendatacam` working for testing on `Ubuntu` running in `WSL2`.
Installation and running docker works fine. But the initial loading phase does not complete with the following exception.

I have manually verified the uploaded file is in the expected folder inside the container.

### Exception details here
```text
(node:40) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'filename' of undefined
    at /var/local/opendatacam/server.js:990:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### docker-compose.yml file here
```yaml
version: "2.3"
services:
  opendatacam:
    restart: always
    runtime: nvidia
    image: opendatacam/opendatacam:v3.0.2-desktop
    privileged: true
    volumes:
      - './config.json:/var/local/opendatacam/config.json'
      - './opendatacam_videos:/var/local/darknet/opendatacam_videos'
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
```

### Complete log below
```log
> Ready on http://localhost:8080
> Ready on http://172.31.0.3:8080
Success init db
(node:40) [DEP0001] DeprecationWarning: OutgoingMessage.flush is deprecated. Use flushHeaders instead.
Process YOLO started
 CUDA-version: 10020 (12040), cuDNN: 7.6.5, GPU count: 1  
 OpenCV version: 4.1.1
 0 : compute_capability = 890, cudnn_half = 0, GPU: NVIDIA GeForce RTX 4060 Laptop GPU 
   layer   filters  size/strd(dil)      input                output
   0 First request on console stream
uploadMulter callback
File upload done
Stop YOLO
Stop recording
Process YOLO exit
Process YOLO stopped
YOLO stopped
/var/local/darknet/opendatacam_videos_uploaded/demo.mp4
Process YOLO initialized
Process YOLO started
(node:40) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'filename' of undefined
    at /var/local/opendatacam/server.js:990:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 CUDA-version: 10020 (12040), cuDNN: 7.6.5, GPU count: 1  
 OpenCV version: 4.1.1
 0 : compute_capability = 890, cudnn_half = 0, GPU: NVIDIA GeForce RTX 4060 Laptop GPU 
   layer   filters  size/strd(dil)      input                output
   0 New client, close previous stream
New client, close previous stream
```

Thanks in advance.
